### ISSUE TITLE
Plugin Easily Runs Into CSS Problems Due To Generic Class Names

### ISSUE THREAD

**Issue by abass** [rainlab/editable-plugin#17] opened 2015-01-20 22:20 UTC
**EDIT:** The classes `.visible` and `.active` are very general and will easily be overridden if used in the site's css at all. Either on the element that editable is used on (which happened in my case), or if used as a global class. A suggestion to the plugin dev would be to use classes specific to the plugin name like `.editable-visible` and `.editable-active` instead.

This would prevent this problem from ever happening in the future as it's a pretty understandable mixup that I encountered.

~~When I first installed OctoberCMS about a month ago, this plugin was working flawlessly. After updating the build somewhat recently, I noticed that the plugin no longer works. When I hover over the editable text on the front-end, it resizes the scrollbar as if it's trying to do something, but nothing happens.~~

~~All of the proper resources are loading, jquery.js & editable.js as can be seen here:~~

![Proper resources are loading](http://i.imgur.com/wkcp653.png)

~~Not sure what's going on though. Anyone else encountering this problem? Such an essential plugin for my clients to edit their site content.~~

Thanks!

**Comment by KB1RMA** [comment] 2015-01-21 20:15
What build are you on? I can't reproduce this on 182.

**Comment by flip4bytes** [comment] 2015-01-21 20:21
@KB1RMA I too am on 182. Something has definitely broken it for me, not sure what though.. I don't have any errors in console or anything. Maybe I'm just experiencing a really strange bug?

**Comment by KB1RMA** [comment] 2015-01-21 20:57
I'd guess you have CSS or JS interfering with it. I'd rule that out before considering this an official issue.

**Comment by flip4bytes** [comment] 2015-01-21 21:04
@KB1RMA ah, really appreciate the suggestion. I have gone and removed all my CSS from the site and it appears to work. Now finding out exactly what CSS is interfering with it is going to be the tough part.. Not sure where to even start. I'll try and mess around with it though and see where the problem is and update it here.

Thanks!

**Comment by KB1RMA** [comment] 2015-01-21 21:06
Cool. Glad I could help. Might want to mark this as closed though just for organizational sake.

**Comment by flip4bytes** [comment] 2015-01-21 21:30
@KB1RMA Unreal.. Note to self, check what classes plugins are dependant on. I was using `.visible` because it's a good class name to use in CSS, but so does the plugin. Maybe it'd be smarts to give plugins their own special classes like "editable-visible" or something so something like this doesn't happen? I can't be the first or the last person to run into a problem like this.

Thanks again @KB1RMA this has been bugging me for weeks now, sometimes the answer is right infront of your face. I was looking into everything else but the CSS.. Why I did that is beyond me.. Stupid me.

**Comment by daftspunk** [comment] 2015-05-16 08:07
Yes, these classes should probably be prefixed too.

**Comment by LukeTowers** [comment] 2017-10-26 23:00
Closing as it has been over a month since any activity on this occurred.

**Closed by LukeTowers** 2017-10-26 23:00 UTC
